SELECT TEAM_NAME, COUNT(*) AS GAME_COUNT
FROM (
    SELECT TEAM_NAME_HOME AS TEAM_NAME
    FROM SOCCER.TBL_UEFA_2021
    WHERE POSSESSION_HOME > POSSESSION_AWAY

    UNION ALL

    SELECT TEAM_NAME_AWAY AS TEAM_NAME
    FROM SOCCER.TBL_UEFA_2021
    WHERE POSSESSION_AWAY > POSSESSION_HOME
)
GROUP BY TEAM_NAME
ORDER BY GAME_COUNT DESC
LIMIT 1;